/**
 * policy.h — GENERATED by export_policy_c.py from runs/race/sparse_rpm_seed0.
 * Do not edit by hand; re-run the exporter instead.
 *
 * Actor-only forward pass (deterministic mean, no log_std/critic — see
 * export_policy_c.py's module docstring). Source checkpoint: task='race'
 * action_type='rpm' obs_fn='v3'
 * hidden=[128, 128] activation='tanh'
 */
#ifndef POLICY_H
#define POLICY_H

#define POLICY_OBS_DIM 21
#define POLICY_ACTION_DIM 4

/**
 * Deterministic actor forward pass: obs[POLICY_OBS_DIM] -> actionOut[POLICY_ACTION_DIM].
 * actionOut is the raw (unsquashed) mean — caller must clip to [-1, 1]
 * itself (matching training-time env.step()'s own clip; see
 * mix_rpm_action/mixAttitudeRpm's docstrings, which assume a pre-clipped
 * input). Not thread-safe to call concurrently (no internal state, but not
 * guarded) — fine for the single control-loop-task use case this is for.
 */
void policyForward(const float obs[POLICY_OBS_DIM], float actionOut[POLICY_ACTION_DIM]);

#endif // POLICY_H
