/**
 * policy.h — GENERATED by export_policy_c.py from runs/hof/sparse_attitude_seed0.
 * Do not edit by hand; re-run the exporter instead.
 *
 * Actor-only forward pass (deterministic mean, no log_std/critic — see
 * export_policy_c.py's module docstring). Source checkpoint: task='race'
 * action_type='attitude' obs_fn='v3'
 * hidden=[128, 128] activation='tanh'
 */
#ifndef POLICY_H
#define POLICY_H

#include <stdint.h>
#include <stdbool.h>

#define POLICY_OBS_DIM 21
#define POLICY_ACTION_DIM 4
#define POLICY_NUM_LAYERS 3
#define POLICY_TOTAL_FLOATS 19844
#define POLICY_TOTAL_BYTES (POLICY_TOTAL_FLOATS * 2u)  // fp16 (uint16_t bits) = 2 bytes/value
#define POLICY_HEADER_BYTES 24u
#define POLICY_WEIGHTS_MAGIC 0x324C4F50u

/**
 * Deterministic actor forward pass: obs[POLICY_OBS_DIM] -> actionOut[POLICY_ACTION_DIM].
 * actionOut is the raw (unsquashed) mean — caller must clip to [-1, 1]
 * itself (matching training-time env.step()'s own clip; see
 * mix_rpm_action/mixAttitudeRpm's docstrings, which assume a pre-clipped
 * input). Not thread-safe to call concurrently (no internal state, but not
 * guarded) — fine for the single control-loop-task use case this is for.
 * Always reads whatever's currently in g_weights — see policyWeightsValid()
 * below; callers (race_controller.c) must check that before trusting the
 * output is anything other than stale/undefined.
 */
void policyForward(const float obs[POLICY_OBS_DIM], float actionOut[POLICY_ACTION_DIM]);

/**
 * True iff g_weights currently holds a fully-uploaded, CRC-validated
 * weight set — true from boot (the compiled-in checkpoint below counts),
 * false for the duration of an in-progress upload (see policyWeightsWrite),
 * and false again if an upload's CRC fails to validate (the previous,
 * still-good weights are left untouched in that case, but the flag itself
 * reports false until a fresh, valid upload completes — a conservative
 * "don't trust an unverified state" choice, not a claim g_weights is
 * actually corrupted).
 */
bool policyWeightsValid(void);

/**
 * Total addressable size (bytes) of the conceptual [header ++ payload]
 * memory region policyWeightsWrite() accepts writes into — what
 * policy_mem.c's MEM_TYPE_APP handler reports from getSize().
 */
uint32_t policyMemSize(void);

/**
 * Handle one raw byte-range write from policy_mem.c's MEM_TYPE_APP write
 * callback, at the given absolute address within [0, policyMemSize()).
 * See policy.c's module docstring for the full upload protocol (header
 * reassembly + validation, then payload bytes streamed straight into
 * g_weights, then a final CRC check) and policySetArmed() for why this
 * rejects every call while armed. Returns false (write rejected, no state
 * changed beyond what's documented) on: armed, address out of range, or —
 * once enough bytes have arrived to attempt it — a header that fails to
 * validate against this firmware's compiled-in architecture.
 */
bool policyWeightsWrite(uint32_t memAddr, uint32_t writeLen, const uint8_t* data);

/**
 * Mirrors race_controller.c's obsChannelEnable (see that file) into
 * policy.c, so policyWeightsWrite() can refuse uploads while the control
 * loop might be reading g_weights — race_controller.c calls this once per
 * tick; policy_mem.c never needs to know about ctrlRace's param group
 * directly.
 */
void policySetArmed(bool armed);
bool policyIsArmed(void);

#endif // POLICY_H
