/**
 * test_policy_host.c — standalone host-side check of policy.c: the forward
 * pass against a reference computed directly from the exported checkpoint
 * (mjc_dronetests/runs/hof/sparse_attitude_seed0), and the full
 * policyWeightsWrite() upload protocol (chunked delivery, CRC/architecture
 * rejection, recovery after a rejected attempt, the armed gate). Same
 * pattern as test_mixer_host.c — pure C99, no CF/FreeRTOS dependencies:
 *
 *   gcc -std=c99 -Wall -Wextra -I. test_policy_host.c policy.c -o test_policy_host -lm
 *   ./test_policy_host <fixtures_dir>
 *
 * Fixtures (weights_original.bin, weights_perturbed.bin, weights_bad_crc.bin,
 * weights_bad_dims.bin, weights_bad_magic.bin) and the reference action
 * values below were generated by mjc_dronetests' make_test_fixtures.py
 * against the same checkpoint policy.c/h were exported from — regenerate
 * both together if the checkpoint ever changes.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "policy.h"

static int failures = 0;

static void checkf(const char *name, float got, float want) {
    float diff = fabsf(got - want);
    float tol = fmaxf(1e-4f * fabsf(want), 1e-3f);
    if (diff > tol) {
        printf("FAIL %-40s got=%.6f want=%.6f diff=%.6f\n", name, got, want, diff);
        failures++;
    } else {
        printf("ok   %-40s got=%.6f want=%.6f\n", name, got, want);
    }
}

static void checkb(const char *name, bool got, bool want) {
    if (got != want) {
        printf("FAIL %-40s got=%d want=%d\n", name, got, want);
        failures++;
    } else {
        printf("ok   %-40s got=%d\n", name, got);
    }
}

static unsigned char *readFile(const char *path, long *lenOut) {
    FILE *f = fopen(path, "rb");
    if (!f) { printf("FAIL could not open %s\n", path); failures++; return NULL; }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    unsigned char *buf = malloc((size_t)len);
    if (fread(buf, 1, (size_t)len, f) != (size_t)len) { printf("FAIL short read %s\n", path); failures++; }
    fclose(f);
    *lenOut = len;
    return buf;
}

// Feeds a full blob into policyWeightsWrite() in small, deliberately
// boundary-misaligned chunks (chunkSize=19, not a divisor of
// POLICY_HEADER_BYTES or of any layer size) -- simulates real CRTP mem
// write chunking, which has no reason to align with policy.c's internal
// layout. Returns the return value of the LAST chunk's call (the one that
// completes the header, or that completes the payload, is where a
// rejection actually surfaces).
static bool feedBlob(const unsigned char *data, long len, unsigned chunkSize) {
    bool lastResult = true;
    for (long off = 0; off < len; off += chunkSize) {
        unsigned n = (unsigned)((len - off < chunkSize) ? (len - off) : chunkSize);
        lastResult = policyWeightsWrite((uint32_t)off, (uint8_t)n, data + off);
        if (!lastResult && off + n < len) {
            // Rejected mid-transfer (e.g. bad header) -- stop early, same
            // as a real host would on a write failure.
            return false;
        }
    }
    return lastResult;
}

int main(int argc, char **argv) {
    if (argc < 2) {
        printf("usage: %s <fixtures_dir>\n", argv[0]);
        return 2;
    }
    char path[1024];

    const float testObs[POLICY_OBS_DIM] = {
        0.547912121f, -0.122243121f, 0.717195868f, 0.394736052f, -0.811645329f,
        0.951244712f, 0.522279382f, 0.572128594f, -0.743772745f, -0.0992281213f,
        -0.258403957f, 0.85352999f, 0.287730247f, 0.64552325f, -0.1131716f,
        -0.545522571f, 0.109169573f, -0.872365475f, 0.655262351f, 0.263328791f,
        0.516175508f
    };
    const float refOriginal[POLICY_ACTION_DIM] = {-1.37123477f, -2.24993825f, 4.07843256f, -2.42866635f};
    const float refPerturbed[POLICY_ACTION_DIM] = {14.1163149f, 12.5264902f, 12.453764f, 13.4560986f};

    printf("--- compiled-in default weights ---\n");
    checkb("policyWeightsValid at boot", policyWeightsValid(), true);
    checkb("policyIsArmed at boot", policyIsArmed(), false);
    {
        float action[POLICY_ACTION_DIM];
        policyForward(testObs, action);
        checkf("action[0] (compiled-in)", action[0], refOriginal[0]);
        checkf("action[1] (compiled-in)", action[1], refOriginal[1]);
        checkf("action[2] (compiled-in)", action[2], refOriginal[2]);
        checkf("action[3] (compiled-in)", action[3], refOriginal[3]);
    }

    printf("--- valid upload (weights_perturbed.bin), chunked ---\n");
    {
        snprintf(path, sizeof(path), "%s/weights_perturbed.bin", argv[1]);
        long len;
        unsigned char *blob = readFile(path, &len);
        bool ok = feedBlob(blob, len, 19);
        checkb("feedBlob accepted", ok, true);
        checkb("policyWeightsValid after upload", policyWeightsValid(), true);
        float action[POLICY_ACTION_DIM];
        policyForward(testObs, action);
        checkf("action[0] (perturbed)", action[0], refPerturbed[0]);
        checkf("action[1] (perturbed)", action[1], refPerturbed[1]);
        checkf("action[2] (perturbed)", action[2], refPerturbed[2]);
        checkf("action[3] (perturbed)", action[3], refPerturbed[3]);
        free(blob);
    }

    printf("--- upload rejected while armed ---\n");
    {
        policySetArmed(true);
        snprintf(path, sizeof(path), "%s/weights_original.bin", argv[1]);
        long len;
        unsigned char *blob = readFile(path, &len);
        bool firstChunkOk = policyWeightsWrite(0, 19, blob);
        checkb("write rejected while armed", firstChunkOk, false);
        checkb("still valid (untouched)", policyWeightsValid(), true);
        float action[POLICY_ACTION_DIM];
        policyForward(testObs, action);
        checkf("action[0] unchanged (still perturbed)", action[0], refPerturbed[0]);
        policySetArmed(false);
        free(blob);
    }

    printf("--- bad magic rejected at header stage ---\n");
    {
        snprintf(path, sizeof(path), "%s/weights_bad_magic.bin", argv[1]);
        long len;
        unsigned char *blob = readFile(path, &len);
        bool ok = feedBlob(blob, len, 19);
        checkb("bad-magic upload rejected", ok, false);
        free(blob);
    }

    printf("--- bad architecture (obsDim) rejected at header stage ---\n");
    {
        snprintf(path, sizeof(path), "%s/weights_bad_dims.bin", argv[1]);
        long len;
        unsigned char *blob = readFile(path, &len);
        bool ok = feedBlob(blob, len, 19);
        checkb("bad-dims upload rejected", ok, false);
        free(blob);
    }

    printf("--- recovery: valid upload after two rejected header attempts ---\n");
    {
        snprintf(path, sizeof(path), "%s/weights_original.bin", argv[1]);
        long len;
        unsigned char *blob = readFile(path, &len);
        bool ok = feedBlob(blob, len, 19);
        checkb("feedBlob accepted after prior rejections", ok, true);
        checkb("policyWeightsValid after recovery upload", policyWeightsValid(), true);
        float action[POLICY_ACTION_DIM];
        policyForward(testObs, action);
        checkf("action[0] (back to original)", action[0], refOriginal[0]);
        checkf("action[1] (back to original)", action[1], refOriginal[1]);
        free(blob);
    }

    printf("--- bad CRC: payload writes succeed, final validity is false ---\n");
    {
        snprintf(path, sizeof(path), "%s/weights_bad_crc.bin", argv[1]);
        long len;
        unsigned char *blob = readFile(path, &len);
        bool ok = feedBlob(blob, len, 19);
        // The write calls themselves succeed (header validates fine, every
        // byte is in-range) -- it's the *content* that's wrong, only
        // detectable once the full payload has arrived and the CRC is
        // checked. See policy.h's policyWeightsValid() docstring: this
        // does NOT promise g_weights keeps its old value on a CRC failure,
        // only that the valid flag correctly reports false so callers
        // never trust it — verified by the flag check below, not by
        // asserting anything about policyForward's output here.
        checkb("feedBlob write calls succeeded", ok, true);
        checkb("policyWeightsValid after bad-CRC upload", policyWeightsValid(), false);
        free(blob);
    }

    printf("--- final recovery after bad CRC ---\n");
    {
        snprintf(path, sizeof(path), "%s/weights_original.bin", argv[1]);
        long len;
        unsigned char *blob = readFile(path, &len);
        bool ok = feedBlob(blob, len, 19);
        checkb("feedBlob accepted after bad-CRC recovery", ok, true);
        checkb("policyWeightsValid after final recovery", policyWeightsValid(), true);
        float action[POLICY_ACTION_DIM];
        policyForward(testObs, action);
        checkf("action[0] (final, original)", action[0], refOriginal[0]);
        free(blob);
    }

    if (failures == 0) {
        printf("ALL_POLICY_CHECKS_PASSED\n");
        return 0;
    } else {
        printf("%d CHECK(S) FAILED\n", failures);
        return 1;
    }
}
